### ISSUE TITLE
Process 1 terminated with the following error

### ISSUE THREAD

**Issue by ghost** [Kai-46/nerfplusplus#49]
2022-11-18 23:46:13,697 [INFO] root: tat_training_Truck step: 0  resolution: 1.000000 level_0/loss: 0.064675 level_0/pnsr: 11.892565 level_1/loss: 0.064430 level_1/pnsr: 11.909071 iter_time: 0.250360
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/~~/anaconda3/envs/nerfplusplus/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/~~/anaconda3/envs/nerfplusplus/lib/python3.6/site-packages/tensorboardX/event_file_writer.py", line 202, in run
    data = self._queue.get(True, queue_wait_duration)
  File "/~~/anaconda3/envs/nerfplusplus/lib/python3.6/multiprocessing/queues.py", line 108, in get
    res = self._recv_bytes()
  File "/~~/anaconda3/envs/nerfplusplus/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/~~/anaconda3/envs/nerfplusplus/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/~~/anaconda3/envs/nerfplusplus/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

Traceback (most recent call last):
  File "ddp_train_nerf.py", line 604, in <module>
    train()
  File "ddp_train_nerf.py", line 599, in train
    join=True)
  File "/~~/anaconda3/envs/nerfplusplus/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/~~/anaconda3/envs/nerfplusplus/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/~~/anaconda3/envs/nerfplusplus/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/~~/anaconda3/envs/nerfplusplus/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/~~/nerfplusplus-master/ddp_train_nerf.py", line 488, in ddp_train_nerf
    idx = what_val_to_log % len(val_ray_samplers)
ZeroDivisionError: integer division or modulo by zero

how to realise the problem,could you help me

**Comment by shuimoqingyin** [comment]
I run the code with the two GPUs of 2080Ti or four GPUs of 3090,but find the same question

**Comment by shuimoqingyin** [comment]
Traceback (most recent call last):
  File "ddp_train_nerf.py", line 604, in <module>
    train()
  File "ddp_train_nerf.py", line 599, in train
    join=True)
  File "/data2/lijie/anaconda3/envs/nerfplusplus/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/data2/lijie/anaconda3/envs/nerfplusplus/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/data2/lijie/anaconda3/envs/nerfplusplus/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/data2/lijie/anaconda3/envs/nerfplusplus/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/data2/lijie/nerfplusplus-master/ddp_train_nerf.py", line 371, in ddp_train_nerf
    try_load_min_depth=args.load_min_depth)
  File "/data2/lijie/nerfplusplus-master/data_loader_split.py", line 81, in load_data_split
    train_imgfile = find_files('{}/{}/train/rgb'.format(basedir, scene), exts=['*.png', '*.jpg'])[0]
IndexError: list index out of range


Who can help me solve the problem

**Comment by shuimoqingyin** [comment]
Traceback (most recent call last):
  File "ddp_train_nerf.py", line 604, in <module>
    train()
  File "ddp_train_nerf.py", line 599, in train
    join=True)
  File "/.../.../anaconda3/envs/nerfplusplus/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/.../.../anaconda3/envs/nerfplusplus/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/.../.../anaconda3/envs/nerfplusplus/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/.../.../anaconda3/envs/nerfplusplus/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/.../.../nerfplusplus-master/ddp_train_nerf.py", line 371, in ddp_train_nerf
    try_load_min_depth=args.load_min_depth)
  File "/.../.../nerfplusplus-master/data_loader_split.py", line 81, in load_data_split
    train_imgfile = find_files('{}/{}/train/rgb'.format(basedir, scene), exts=['*.png', '*.jpg'])[0]
IndexError: list index out of range

Who can help me solve the problem?

**Comment by ElderBacon** [comment]
Same question, Every setting is default and I make sure that I have followed the routine written in the README.md, Any help would be thank.

**Comment by chuguo01** [comment]
You can refer to #2 to solve your problem, or just edit the argument from "validation" to "test" like below:
<img width="566" alt="image" src="https://user-images.githubusercontent.com/78773047/204100244-4870d641-fd59-4ac3-822d-2e0f0406904e.png">
